# Generated by Django 5.0.3 on 2024-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_category_auction_bid_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.RemoveField(
            model_name="auction",
            name="category",
        ),
        migrations.AddField(
            model_name="auction",
            name="categories",
            field=models.ManyToManyField(
                related_name="categories_auctions", to="auctions.category"
            ),
        ),
    ]
