# Generated by Django 5.0.3 on 2024-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_alter_bid_listing_alter_comment_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
