# Generated by Django 5.0.3 on 2024-03-27 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_alter_listing_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
